# Generated by Django 3.2.9 on 2021-11-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211125_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='runtime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
