# Generated by Django 3.2.9 on 2021-11-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_content_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=1),
        ),
    ]
